Programs on stacks, queues and recursion.
Vishruth-S/CompetitiveCode pull request #303
Opened 2020-10-09 12:16 UTC by shreayan98c

2020-10-09 17:13 UTC, Vishruth-S requested changes

2020-10-09 17:13 UTC, Vishruth-S commented on Misc/SumOfAllDigits/problem.md
> +3
It would be better if you could add 1-2 more testcases and also provide an explanation to atleast 1 😅

2020-10-10 05:27 UTC, shreayan98c commented
Added test cases and provided an explanation to them.

2020-10-10 09:44 UTC, Vishruth-S approved these changes
Awesome 👍 Thanks for your contribution 😄 

Also I have formatted the problem and made it more readable. Hope that's okay 🙃

2020-10-10 09:44 UTC, merged