Symmetric traversal of BinaryTree
Vishruth-S/CompetitiveCode pull request #402
Opened 2020-10-17 08:15 UTC by bplm

Hey there!, Thanks for submitting a PR to this repo :smiley:  
Please complete the following checklist for your PR to be approved. Mark the items by adding an `x`.   
Example:  - [ ] Mark me as completed  
To mark: - [x] Mark me as completed

- [x ] My Pull Request adheres to the Contribution guidelines.
- [x] I have added `problem.md` and `solution` files in the appropriate folder
- [x] In `problem.md` I have provided a correct link to the problem.  
  (In case you are not adding a problem, you can freely mark this as complete)
- [x] My solution passes all the testcases within the given constraints.
- [x] I have properly indented and documented my solution using comments.

If any of the above is unmarked, please make the necessary changes and then mark them so that you're PR can be approved and merged.  
(Only completed checklist PRs will be reviewed)

2020-10-17 16:49 UTC, Vishruth-S requested changes
If you are adding multiple problems, please create separate folders for them.

2020-10-17 17:13 UTC, bplm commented
> If you are adding multiple problems, please create separate folders for them.

@Vishruth-S  Please can you check now? I have created folderwise problems along with their solutions.
Thanks!!

2020-10-18 05:08 UTC, bplm commented
@Vishruth-S  Can you please check   now.
https://github.com/Vishruth-S/CompetitiveCode/pull/402/commits/2738dbc865d2118a066de7234abfa9a90116c381

2020-10-18 10:55 UTC, Vishruth-S approved these changes

2020-10-18 10:55 UTC, merged